name: odin
description: "A notes aplication"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.0.1
  shared_preferences: ^2.2.3
  email_validator: ^2.1.17
  introduction_screen: ^3.1.14
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/transparentImg.png
    - assets/notesPaperBG.jpg
    - assets/app_logo.jpg
    - assets/QAButtons/
    - assets/icons/
    - assets/introduction/